<?php


/**
 * @file
 * wysiwyg_spellcheck is a plugin for wysiwyg editors
 */

function _wysiwyg_spellcheck_default_path() {
  return
    function_exists('wysiwyg_get_path') 
	  ? wysiwyg_get_path('tinymce') . '/jscripts/tiny_mce/plugins/spellchecker'
      : 'sites/all/libraries/tinymce/jscripts/tiny_mce/plugins/spellchecker';
}

/**
 * Implementation of hook_help().
 */
function wysiwyg_spellcheck_help($path, $arg) {
  if ($path == 'admin/modules#description') {
    return t('Enables TinyMCE spellchecker plugin in Wysiwyg editor.');
  }
}

/**
* Implementation of hook_wysiwyg_plugin().
*/
function wysiwyg_spellcheck_wysiwyg_plugin($editor) {
  switch ($editor) {
    case 'tinymce':
//if ($version > 3) {
//      $path = drupal_get_path('module', 'wysiwyg_spellcheck');
      $path = variable_get('wysiwyg_spellcheck_tinymce_spellchecker_location', _wysiwyg_spellcheck_default_path());
      if (file_exists("$path/editor_plugin.js")) return array(
// SEE http://drupal.org/files/issues/wysiwyg_api_documentation.patch
        'spellchecker' => array(
// SEE http://drupal.org/node/767550
          'path' => $path,
          'filename' => 'editor_plugin.js',
          'buttons' => array('spellchecker' => t('Spell Check')),
          'url' => 'http://wiki.moxiecode.com/index.php/TinyMCE:Plugins/spellchecker',
          'load' => TRUE,
        ),
      );
//}	// if ($version)
  }
}

/**
 * Implementation of hook_init().
 */
function wysiwyg_spellcheck_init() {
//  $path = drupal_get_path('module', 'wysiwyg_spellcheck');
//  drupal_add_js($path . '/tinymce/spellchecker/any.js');
//  drupal_add_js('var anyvar = "/' . $path . '/mimetex/mimetex.cgi";', 'inline');
}
